// Mock data for eventapp Web B2C — Poznań events
// Map coords are in 0..1000 (x), 0..720 (y) — for our stylized SVG map canvas.

const CATEGORIES = [
  { id: 'live',     label: 'Live now',   icon: 'Flame',    color: 'var(--live-red)',     special: true },
  { id: 'music',    label: 'Muzyka',     icon: 'Music',    color: 'var(--cat-music)'    },
  { id: 'club',     label: 'Klub',       icon: 'Disc',     color: 'var(--cat-club)'     },
  { id: 'art',      label: 'Sztuka',     icon: 'Palette',  color: 'var(--cat-art)'      },
  { id: 'food',     label: 'Jedzenie',   icon: 'Utensils', color: 'var(--cat-food)'     },
  { id: 'sport',    label: 'Sport',      icon: 'Trophy',   color: 'var(--cat-sport)'    },
  { id: 'theatre',  label: 'Teatr',      icon: 'Drama',    color: 'var(--cat-theatre)'  },
  { id: 'comedy',   label: 'Komedia',    icon: 'Laugh',    color: 'var(--cat-comedy)'   },
  { id: 'tech',     label: 'Tech',       icon: 'Cpu',      color: 'var(--cat-tech)'     },
  { id: 'film',     label: 'Film',       icon: 'Film',     color: 'var(--cat-film)'     },
  { id: 'festival', label: 'Festiwal',   icon: 'Sparkles', color: 'var(--cat-festival)' },
  { id: 'wellness', label: 'Wellness',   icon: 'Leaf',     color: 'var(--cat-wellness)' },
  { id: 'kids',     label: 'Dzieci',     icon: 'Baby',     color: 'var(--cat-kids)'     },
];

const CITIES = [
  { id: 'poznan',   name: 'Poznań',     count: 247, region: 'Wielkopolska' },
  { id: 'krakow',   name: 'Kraków',     count: 412, region: 'Małopolska' },
  { id: 'warszawa', name: 'Warszawa',   count: 638, region: 'Mazowsze' },
  { id: 'wroclaw',  name: 'Wrocław',    count: 298, region: 'Dolny Śląsk' },
  { id: 'gdansk',   name: 'Gdańsk',     count: 184, region: 'Pomorze' },
  { id: 'lodz',     name: 'Łódź',       count: 156, region: 'Łódzkie' },
  { id: 'katowice', name: 'Katowice',   count: 128, region: 'Śląsk' },
  { id: 'lublin',   name: 'Lublin',     count: 92,  region: 'Lubelskie' },
  { id: 'szczecin', name: 'Szczecin',   count: 78,  region: 'Pomorze Zach.' },
];

// Mock photos — reuse the 3 sample images, with deterministic Unsplash URLs as fallback
const IMG = {
  jazz:   'assets/sample-event-jazz.jpg',
  rock:   'assets/sample-event-rock.jpg',
  techno: 'assets/sample-event-techno.jpg',
  venue:  'assets/sample-venue-klub-stodola.jpg',
};

const EVENTS = [
  {
    id: 'e1',
    title: 'Nils Frahm — All Encores Tour',
    cat: 'music',
    venue: { id: 'v1', name: 'Aula UAM', address: 'Wieniawskiego 1' },
    image: IMG.jazz,
    date: 'Sob, 24 maja',
    time: '20:00',
    dateShort: { d: 24, m: 'maj' },
    priceFrom: 189,
    badges: ['fast'],
    coords: { x: 480, y: 310 },
    hashtags: ['#neoclassical', '#piano', '#ambient'],
    desc: 'Niemiecki kompozytor i pianista po raz pierwszy w Poznaniu. Dwie godziny improwizacji na fortepianie, syntezatorach i organach. Wieczór, który zostaje w głowie na długo.',
  },
  {
    id: 'e2',
    title: 'Smolik / Kev Fox — Solidarni z Ukrainą',
    cat: 'music',
    venue: { id: 'v2', name: 'Tama', address: 'Szyperska 3' },
    image: IMG.rock,
    date: 'Sob, 24 maja',
    time: '21:30',
    dateShort: { d: 24, m: 'maj' },
    priceFrom: 129,
    badges: ['live'],
    coords: { x: 620, y: 220 },
    hashtags: ['#indie', '#live', '#charity'],
    desc: 'Smolik i Kev Fox spotykają się na scenie po raz pierwszy w tym roku. Cały dochód z biletów trafia do Fundacji Pomocy Ukrainie.',
  },
  {
    id: 'e3',
    title: 'Techno Tuesday: Recondite (live)',
    cat: 'club',
    venue: { id: 'v3', name: 'SQ Klub', address: 'Wenecjańska 9' },
    image: IMG.techno,
    date: 'Wt, 27 maja',
    time: '23:00',
    dateShort: { d: 27, m: 'maj' },
    priceFrom: 80,
    badges: ['recur'],
    tipBy: '@kasiazpoznania',
    coords: { x: 380, y: 410 },
    hashtags: ['#techno', '#live', '#afterhours'],
    desc: 'Cotygodniowa noc techno w SQ. Tym razem na żywo Recondite — mistrz minimalistycznego, melancholijnego brzmienia.',
  },
  {
    id: 'e4',
    title: 'Wystawa: Wojciech Fangor — Powierzchnie',
    cat: 'art',
    venue: { id: 'v4', name: 'Muzeum Narodowe', address: 'Aleje Marcinkowskiego 9' },
    image: IMG.jazz,
    date: 'Codziennie do 30 cze',
    time: '10:00–18:00',
    dateShort: { d: 25, m: 'maj' },
    priceFrom: 0,
    badges: ['free'],
    coords: { x: 540, y: 380 },
    hashtags: ['#opart', '#malarstwo', '#wystawa'],
    desc: 'Retrospektywa jednego z najważniejszych polskich artystów XX wieku. 60 obrazów, instalacja site-specific w nowym skrzydle muzeum.',
  },
  {
    id: 'e5',
    title: 'Lech vs Legia — Ekstraklasa',
    cat: 'sport',
    venue: { id: 'v5', name: 'Stadion Poznań', address: 'Bułgarska 17' },
    image: IMG.rock,
    date: 'Nd, 25 maja',
    time: '17:30',
    dateShort: { d: 25, m: 'maj' },
    priceFrom: 65,
    badges: ['fast'],
    coords: { x: 180, y: 460 },
    hashtags: ['#ekstraklasa', '#kolejorz'],
    desc: 'Derby z Legią o utrzymanie pozycji w czołówce. Trybuny wyprzedane w 80%.',
  },
  {
    id: 'e6',
    title: 'Open\'er Festival 2026 — pre-party',
    cat: 'festival',
    venue: { id: 'v6', name: 'Skwer Modra Mleczarnia', address: 'Stary Rynek 84' },
    image: IMG.techno,
    date: 'Pt, 30 maja',
    time: '19:00',
    dateShort: { d: 30, m: 'maj' },
    priceFrom: 0,
    badges: ['free'],
    coords: { x: 500, y: 360 },
    hashtags: ['#festival', '#preparty', '#summer'],
    desc: 'Oficjalna rozgrzewka przed Open\'er 2026. DJ-e z line-upu, food trucki, wystawa fotograficzna.',
  },
  {
    id: 'e7',
    title: 'Stand-up: Kacper Ruciński — Nowy program',
    cat: 'comedy',
    venue: { id: 'v7', name: 'Klub Stodoła', address: 'Bukowska 16' },
    image: IMG.jazz,
    date: 'Czw, 29 maja',
    time: '19:30',
    dateShort: { d: 29, m: 'maj' },
    priceFrom: 95,
    badges: [],
    coords: { x: 320, y: 290 },
    hashtags: ['#standup', '#komedia'],
    desc: 'Premiera nowego materiału jednego z najpopularniejszych polskich komików. 90 minut nowych obserwacji o życiu w Polsce 2026.',
  },
  {
    id: 'e8',
    title: 'Pierogi Festival — degustacje z całej Polski',
    cat: 'food',
    venue: { id: 'v8', name: 'Plac Wolności', address: 'Plac Wolności' },
    image: IMG.rock,
    date: 'Sob–Nd, 24–25 maja',
    time: '12:00–22:00',
    dateShort: { d: 24, m: 'maj' },
    priceFrom: 0,
    badges: ['free', 'recur'],
    coords: { x: 460, y: 340 },
    hashtags: ['#pierogi', '#streetfood', '#weekend'],
    desc: '24 odmiany pierogów od 18 restauracji. Warsztaty lepienia dla dzieci, koncerty zespołów ludowych, konkursy.',
  },
  {
    id: 'e9',
    title: 'Hamlet — reż. Krystian Lupa',
    cat: 'theatre',
    venue: { id: 'v9', name: 'Teatr Polski', address: '27 Grudnia 8/10' },
    image: IMG.techno,
    date: 'Pt, 30 maja',
    time: '19:00',
    dateShort: { d: 30, m: 'maj' },
    priceFrom: 75,
    badges: [],
    coords: { x: 420, y: 320 },
    hashtags: ['#teatr', '#shakespeare'],
    desc: 'Reinterpretacja Hamleta w reżyserii Krystiana Lupy. Spektakl trwa 4 godziny z dwiema przerwami.',
  },
  {
    id: 'e10',
    title: 'AI Summit Poznań — startup pitch night',
    cat: 'tech',
    venue: { id: 'v10', name: 'Concordia Design', address: 'Zwierzyniecka 3' },
    image: IMG.jazz,
    date: 'Śr, 28 maja',
    time: '18:00',
    dateShort: { d: 28, m: 'maj' },
    priceFrom: 0,
    badges: ['free'],
    tipBy: '@tomasz_dev',
    coords: { x: 580, y: 250 },
    hashtags: ['#ai', '#startup', '#pitch'],
    desc: '12 startupów AI prezentuje się przed inwestorami i mentorami. Networking, otwarty bar, demo zone.',
  },
  {
    id: 'e11',
    title: 'Noc Muzeów 2026',
    cat: 'art',
    venue: { id: 'v11', name: 'Cała Poznań', address: 'Różne lokalizacje' },
    image: IMG.techno,
    date: 'Sob, 24 maja',
    time: '18:00–02:00',
    dateShort: { d: 24, m: 'maj' },
    priceFrom: 0,
    badges: ['free', 'live'],
    coords: { x: 700, y: 400 },
    hashtags: ['#nocmuzeów', '#kultura'],
    desc: '32 muzea i galerie otwarte przez całą noc. Specjalne oprowadzania, warsztaty, performances.',
  },
  {
    id: 'e12',
    title: 'Yoga w Parku Sołackim — sunrise flow',
    cat: 'wellness',
    venue: { id: 'v12', name: 'Park Sołacki', address: 'Wielka Solna' },
    image: IMG.rock,
    date: 'Nd, 25 maja',
    time: '07:00',
    dateShort: { d: 25, m: 'maj' },
    priceFrom: 25,
    badges: ['recur'],
    coords: { x: 280, y: 200 },
    hashtags: ['#yoga', '#sunrise', '#mindfulness'],
    desc: 'Cotygodniowa sesja porannej yogi na otwartej trawie. Mat-y zapewniamy, kawa po sesji w cenie.',
  },
];

const VENUE_DETAILS = {
  v3: {
    id: 'v3',
    name: 'SQ Klub',
    category: 'Klub muzyczny',
    address: 'Wenecjańska 9, 61-108 Poznań',
    description: 'SQ Klub to jedno z najbardziej rozpoznawalnych miejsc na poznańskiej mapie elektroniki. Od 2014 roku gospodarz cotygodniowych nocy techno i house, a także rezydencji takich jak Concrete Soul i Modular. Trzy sale, dwa system soundu, dach dostępny w sezonie.',
    followers: '4 280',
    photo: IMG.venue,
    coords: { x: 380, y: 410 },
    upcoming: ['e3'],
    hours: [
      ['Poniedziałek', 'zamknięte'],
      ['Wtorek', '23:00 – 06:00'],
      ['Środa', 'zamknięte'],
      ['Czwartek', '23:00 – 06:00'],
      ['Piątek', '23:00 – 07:00'],
      ['Sobota', '23:00 – 07:00'],
      ['Niedziela', 'zamknięte'],
    ],
    todayDay: 'Sobota',
  },
};

Object.assign(window, { CATEGORIES, CITIES, EVENTS, VENUE_DETAILS, IMG });
